name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet test JellyLidarr.sln --configuration Release
      - run: dotnet publish src/Jellyfin.Plugin.JellyLidarr/Jellyfin.Plugin.JellyLidarr.csproj --configuration Release --output artifacts/publish --no-self-contained
